Explicitly provide type for function dictionary
In the case of a single transform in the transforms argument `Dict`,
`transforms` is incorrectly inferring the `Dict` value-type as the
specific transform function singleton type (`#function_name`) rather
than the generic `Function`, causing a `MethodError`, e.g.

```
ERROR: MethodError: no method matching transform(::DataStreams.Data.Schema{true}, ::Dict{Int64,#function_name})
```